/** @type {import('next').NextConfig} */
const nextConfig = {
  reactCompiler: true,

  /* Image optimization disabled for Cloudflare Pages compatibility, but qualities listed to prevent console warnings */
  images: {
    unoptimized: true,
    qualities: [70, 75, 85, 90, 100],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "cdn.sanity.io",
      },
    ],
  },

  /* Security & Performance HTTP Headers */
  async headers() {
    return [
      {
        source: "/images/(.*)",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
      {
        source: "/videos/(.*)",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
      {
        source: "/(.*)",
        headers: [
          { key: "Strict-Transport-Security", value: "max-age=31536000; includeSubDomains; preload" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=()",
          },
        ],
      },
    ];
  },

  /* 301 Redirects — old slugs → final short pain-point slugs */
  async redirects() {
    return [
      // SEO Migration for Category URLs
      { source: "/products/solutions/:slug*", destination: "/products/category/:slug*", permanent: true },
      
      { source: "/products/wall-mount-battery-51-2v-200ah", destination: "/products/lfp-battery-10kwh", permanent: true },
      { source: "/products/wall-mount-battery-51-2v-300ah", destination: "/products/lfp-battery-15kwh", permanent: true },
      { source: "/products/mobile-battery-pack-51-2v-400ah-ls", destination: "/products/mobile-battery-20kwh", permanent: true },
      { source: "/products/mobile-battery-pack-51-2v-314ah", destination: "/products/mobile-battery-16kwh", permanent: true },
      { source: "/products/s-series-battery-gw-51-2-100-b", destination: "/products/rack-battery-10kwh", permanent: true },
      { source: "/products/s-series-battery-gw-51-2-300-b", destination: "/products/rack-battery-15kwh", permanent: true },
      { source: "/products/lithium-battery-51-2v-100ah", destination: "/products/home-battery-5kwh", permanent: true },
      { source: "/products/lithium-battery-51-2v-200ah", destination: "/products/solar-battery-10kwh", permanent: true },
      { source: "/products/lithium-battery-51-2v-314ah", destination: "/products/solar-battery-16kwh", permanent: true },
      { source: "/products/he01-residential-all-in-one-5-5kw-11-16kwh", destination: "/products/all-in-one-solar-5kw", permanent: true },
      { source: "/products/w51100-lifepo4-battery-5-12kwh", destination: "/products/lifepo4-battery-5kwh", permanent: true },
      { source: "/products/hybrid-inverter-hf-6-2kw-48v", destination: "/products/hybrid-inverter-6kw", permanent: true },
      { source: "/products/hybrid-inverter-hf-12kw-48v", destination: "/products/hybrid-inverter-12kw", permanent: true },
      { source: "/products/hybrid-inverter-hf-12kw-48v-ip54", destination: "/products/solar-inverter-12kw-ip54", permanent: true },
      { source: "/products/wall-mounted-inverter-em6200-48l", destination: "/products/wall-inverter-6kw", permanent: true },
      { source: "/products/wall-mounted-inverter-m6200-48pl", destination: "/products/parallel-inverter-6kw", permanent: true },
      { source: "/products/wall-mounted-inverter-em11000-48l", destination: "/products/dual-mppt-inverter-11kw", permanent: true },
      { source: "/products/wall-mounted-inverter-em11000-48l-p", destination: "/products/parallel-inverter-11kw", permanent: true },
      { source: "/products/lead-acid-scooter-72v-20ah-500w", destination: "/products/electric-scooter-500w", permanent: true },
      { source: "/products/youqo-14-inch-scooter-650w", destination: "/products/cargo-scooter-650w", permanent: true },
      { source: "/products/small-folding-ebike-350w", destination: "/products/folding-ebike-350w", permanent: true },
      { source: "/products/war-horse-electric-motorcycle-800w", destination: "/products/electric-motorcycle-800w", permanent: true },
      { source: "/products/big-tank-electric-motorcycle-800w", destination: "/products/heavy-motorcycle-800w", permanent: true },
      { source: "/products/large-folding-ebike-350w", destination: "/products/fat-tyre-ebike-350w", permanent: true },
      { source: "/products/hongtu-electric-motorcycle-800w", destination: "/products/pedal-motorcycle-800w", permanent: true },
      { source: "/products/kugou-electric-scooter-72v-20ah", destination: "/products/fast-scooter-800w", permanent: true },
      { source: "/products/v6-pedal-electric-scooter-800w", destination: "/products/cargo-scooter-800w", permanent: true },
      { source: "/products/v6-pedal-60v-30ah-version", destination: "/products/heavy-scooter-60v", permanent: true },
      { source: "/products/portable-power-station-1000w-2000wh", destination: "/products/power-station-1kw", permanent: true },
      { source: "/products/solar-generator-300w-500w-1000wh", destination: "/products/solar-generator-1kwh", permanent: true },
      { source: "/products/all-in-one-solar-storage-3000w-9570wh", destination: "/products/power-station-3kw", permanent: true },
      { source: "/products/portable-power-station-200-1000w", destination: "/products/portable-power-station-1kw", permanent: true },
      { source: "/products/mav-out-1100-power-station-1000wh", destination: "/products/power-station-led-1kw", permanent: true },
      { source: "/products/compact-power-station-300-600w", destination: "/products/compact-power-station-600w", permanent: true },
      { source: "/products/power-bank-w130-5000mah-wireless", destination: "/products/wireless-powerbank-5000mah", permanent: true },
      { source: "/products/power-bank-w131-10000mah-wireless", destination: "/products/wireless-powerbank-10000mah", permanent: true },
      { source: "/products/power-bank-g151-5000-slim", destination: "/products/slim-powerbank-5000mah", permanent: true },
      { source: "/products/power-bank-g151-5000-built-in-cables", destination: "/products/powerbank-5000mah-cables", permanent: true },
      { source: "/products/power-bank-w151-10000-slim", destination: "/products/slim-powerbank-10000mah", permanent: true },
      { source: "/products/power-bank-w151-10000-built-in-cables", destination: "/products/powerbank-10000mah-cables", permanent: true },
      { source: "/products/power-bank-w152-5000-slim", destination: "/products/powerbank-w152-5000mah", permanent: true },
      { source: "/products/power-bank-w152-5000-built-in-cables", destination: "/products/powerbank-w152-5000mah-cables", permanent: true },
      { source: "/products/power-bank-w152-10000-slim", destination: "/products/powerbank-w152-10000mah", permanent: true },
      { source: "/products/power-bank-w152-10000-built-in-cables", destination: "/products/powerbank-w152-10000mah-cables", permanent: true },
      { source: "/products/power-bank-a148b-5000-aluminum", destination: "/products/powerbank-5000mah-aluminum", permanent: true },
      { source: "/products/power-bank-a158a-5000-aluminum", destination: "/products/ultra-slim-powerbank-5000mah", permanent: true },
      { source: "/products/power-bank-a114b-5000-digital-display", destination: "/products/powerbank-5000mah-display", permanent: true },
      { source: "/products/power-bank-a116b-10000-dual-cell", destination: "/products/powerbank-10000mah-aluminum", permanent: true },
      { source: "/products/power-bank-a154-5000-digital", destination: "/products/powerbank-5000mah-qc30", permanent: true },
      { source: "/products/power-bank-a155-10000-dual-cell-digital", destination: "/products/powerbank-10000mah-digital", permanent: true },
      { source: "/products/power-bank-a156-5000-led", destination: "/products/powerbank-5000mah-led", permanent: true },
      { source: "/products/power-bank-a157-10000-dual-cell-led", destination: "/products/powerbank-10000mah-led", permanent: true },
      { source: "/products/power-bank-a158b-5000-led", destination: "/products/slim-powerbank-5000mah-led", permanent: true },
      { source: "/products/power-bank-a103-10000-digital", destination: "/products/powerbank-10000mah-wireless", permanent: true },
      { source: "/products/power-bank-tk23-with-stand-cables", destination: "/products/powerbank-stand-cables", permanent: true },
      { source: "/products/power-bank-tk15-aluminum-wireless", destination: "/products/powerbank-outage-magsafe-aluminum", permanent: true },
      { source: "/products/power-bank-t18-digital-wireless-stand", destination: "/products/powerbank-outage-wireless-stand", permanent: true },
      { source: "/products/power-bank-t18-led-3c", destination: "/products/powerbank-outage-led-3ports", permanent: true },
      { source: "/products/power-bank-t16-led-3c", destination: "/products/powerbank-outage-led-tripleusb", permanent: true },
      { source: "/products/power-bank-t6-led", destination: "/products/powerbank-outage-led-compact", permanent: true },
      { source: "/products/power-bank-sdr031-10000-led", destination: "/products/powerbank-blackout-10000mah-led", permanent: true },
      { source: "/products/power-bank-sdr032-10000-dual-cell", destination: "/products/powerbank-blackout-10000mah-dual", permanent: true },
      { source: "/products/power-bank-hw032-pink-magnetic", destination: "/products/powerbank-blackout-magnetic-pink", permanent: true },
      { source: "/products/power-bank-hw031-20000mah", destination: "/products/powerbank-blackout-20000mah", permanent: true },
      { source: "/products/solar-power-bank-4-cables-20000mah", destination: "/products/solar-powerbank-20000mah-cables", permanent: true },
      { source: "/products/rugged-solar-power-bank-detachable-cables", destination: "/products/solar-powerbank-rugged-cables", permanent: true },
      { source: "/products/magsafe-solar-power-bank-10000mah", destination: "/products/solar-powerbank-magsafe-10000mah", permanent: true },
      { source: "/products/ultra-slim-solar-power-bank-10000mah", destination: "/products/solar-powerbank-ultraslim", permanent: true },
      { source: "/products/budget-solar-power-bank-18000mah", destination: "/products/solar-powerbank-budget-18000mah", permanent: true },
      { source: "/products/solar-power-bank-with-torch-15000mah", destination: "/products/solar-powerbank-torch-15000mah", permanent: true },
      { source: "/products/basic-solar-power-bank-20000mah", destination: "/products/solar-powerbank-basic-20000mah", permanent: true },
      { source: "/products/ip6-waterproof-solar-power-bank", destination: "/products/solar-powerbank-waterproof-ip6", permanent: true },
      { source: "/products/ip55-waterproof-solar-power-bank", destination: "/products/solar-powerbank-waterproof-ip55", permanent: true },
      { source: "/products/ip66-solar-power-bank-lantern", destination: "/products/solar-powerbank-lantern-ip66", permanent: true },
      { source: "/products/camping-lantern-solar-power-bank", destination: "/products/solar-powerbank-camping-lantern", permanent: true },
      { source: "/products/3-mode-solar-lantern-power-bank", destination: "/products/solar-powerbank-lantern-3mode", permanent: true },
      { source: "/products/solar-bluetooth-speaker-power-bank", destination: "/products/solar-powerbank-bluetooth-speaker", permanent: true },
      { source: "/products/lifepo4-battery-10kwh-nigeria", destination: "/products/lfp-battery-10kwh", permanent: true },
      { source: "/products/lifepo4-battery-15kwh-backup", destination: "/products/lfp-battery-15kwh", permanent: true },
      { source: "/products/mobile-battery-20kwh-offgrid", destination: "/products/mobile-battery-20kwh", permanent: true },
      { source: "/products/portable-battery-16kwh-solar", destination: "/products/mobile-battery-16kwh", permanent: true },
      { source: "/products/rack-battery-10kwh-telecom", destination: "/products/rack-battery-10kwh", permanent: true },
      { source: "/products/rack-battery-15kwh-datacenter", destination: "/products/rack-battery-15kwh", permanent: true },
      { source: "/products/home-solar-battery-5kwh", destination: "/products/home-battery-5kwh", permanent: true },
      { source: "/products/solar-battery-10kwh-backup", destination: "/products/solar-battery-10kwh", permanent: true },
      { source: "/products/industrial-battery-16kwh-solar", destination: "/products/solar-battery-16kwh", permanent: true },
      { source: "/products/all-in-one-solar-5kw-battery", destination: "/products/all-in-one-solar-5kw", permanent: true },
      { source: "/products/dropin-lifepo4-5kwh-ip54", destination: "/products/lifepo4-battery-5kwh", permanent: true },
      { source: "/products/solar-inverter-6kw-nigeria", destination: "/products/hybrid-inverter-6kw", permanent: true },
      { source: "/products/solar-inverter-12kw-backup", destination: "/products/hybrid-inverter-12kw", permanent: true },
      { source: "/products/outdoor-solar-inverter-12kw", destination: "/products/solar-inverter-12kw-ip54", permanent: true },
      { source: "/products/wall-solar-inverter-6kw", destination: "/products/wall-inverter-6kw", permanent: true },
      { source: "/products/parallel-solar-inverter-6kw", destination: "/products/parallel-inverter-6kw", permanent: true },
      { source: "/products/dual-mppt-solar-inverter-11kw", destination: "/products/dual-mppt-inverter-11kw", permanent: true },
      { source: "/products/parallel-solar-inverter-11kw", destination: "/products/parallel-inverter-11kw", permanent: true },
      { source: "/products/electric-scooter-500w-delivery", destination: "/products/electric-scooter-500w", permanent: true },
      { source: "/products/cargo-scooter-650w-nfc", destination: "/products/cargo-scooter-650w", permanent: true },
      { source: "/products/folding-ebike-350w-compact", destination: "/products/folding-ebike-350w", permanent: true },
      { source: "/products/electric-motorcycle-800w-110km", destination: "/products/electric-motorcycle-800w", permanent: true },
      { source: "/products/electric-motorcycle-800w-heavy", destination: "/products/heavy-motorcycle-800w", permanent: true },
      { source: "/products/fat-tyre-ebike-350w-folding", destination: "/products/fat-tyre-ebike-350w", permanent: true },
      { source: "/products/pedal-electric-motorcycle-800w", destination: "/products/pedal-motorcycle-800w", permanent: true },
      { source: "/products/electric-scooter-800w-60kmh", destination: "/products/fast-scooter-800w", permanent: true },
      { source: "/products/cargo-scooter-800w-200kg", destination: "/products/cargo-scooter-800w", permanent: true },
      { source: "/products/heavy-cargo-scooter-60v", destination: "/products/heavy-scooter-60v", permanent: true },
      { source: "/products/power-station-1kw-2kwh", destination: "/products/power-station-1kw", permanent: true },
      { source: "/products/solar-generator-1kwh-ups", destination: "/products/solar-generator-1kwh", permanent: true },
      { source: "/products/power-station-3kw-9kwh", destination: "/products/power-station-3kw", permanent: true },
      { source: "/products/power-station-1kw-portable", destination: "/products/portable-power-station-1kw", permanent: true },
      { source: "/products/power-station-1kw-led", destination: "/products/power-station-led-1kw", permanent: true },
      { source: "/products/power-station-600w-compact", destination: "/products/compact-power-station-600w", permanent: true },
      { source: "/products/wireless-power-bank-5000mah", destination: "/products/wireless-powerbank-5000mah", permanent: true },
      { source: "/products/wireless-power-bank-10000mah", destination: "/products/wireless-powerbank-10000mah", permanent: true },
      { source: "/products/slim-power-bank-5000mah", destination: "/products/slim-powerbank-5000mah", permanent: true },
      { source: "/products/power-bank-5000mah-cables", destination: "/products/powerbank-5000mah-cables", permanent: true },
      { source: "/products/slim-power-bank-10000mah", destination: "/products/slim-powerbank-10000mah", permanent: true },
      { source: "/products/power-bank-10000mah-cables", destination: "/products/powerbank-10000mah-cables", permanent: true },
      { source: "/products/compact-power-bank-5000mah", destination: "/products/powerbank-w152-5000mah", permanent: true },
      { source: "/products/power-bank-5000mah-dual-cable", destination: "/products/powerbank-w152-5000mah-cables", permanent: true },
      { source: "/products/dual-usb-power-bank-10000mah", destination: "/products/powerbank-w152-10000mah", permanent: true },
      { source: "/products/power-bank-10000mah-dual-cable", destination: "/products/powerbank-w152-10000mah-cables", permanent: true },
      { source: "/products/aluminum-power-bank-5000mah", destination: "/products/powerbank-5000mah-aluminum", permanent: true },
      { source: "/products/slim-aluminum-power-bank-5k", destination: "/products/ultra-slim-powerbank-5000mah", permanent: true },
      { source: "/products/display-power-bank-5000mah", destination: "/products/powerbank-5000mah-display", permanent: true },
      { source: "/products/dual-cell-power-bank-10000mah", destination: "/products/powerbank-10000mah-aluminum", permanent: true },
      { source: "/products/digital-qc-power-bank-5000mah", destination: "/products/powerbank-5000mah-qc30", permanent: true },
      { source: "/products/digital-dual-power-bank-10000", destination: "/products/powerbank-10000mah-digital", permanent: true },
      { source: "/products/led-power-bank-5000mah", destination: "/products/powerbank-5000mah-led", permanent: true },
      { source: "/products/led-dual-power-bank-10000mah", destination: "/products/powerbank-10000mah-led", permanent: true },
      { source: "/products/slim-led-power-bank-5000mah", destination: "/products/slim-powerbank-5000mah-led", permanent: true },
      { source: "/products/wireless-digital-power-bank-10k", destination: "/products/powerbank-10000mah-wireless", permanent: true },
      { source: "/products/power-bank-stand-cables", destination: "/products/powerbank-stand-cables", permanent: true },
      { source: "/products/aluminum-magsafe-power-bank", destination: "/products/powerbank-outage-magsafe-aluminum", permanent: true },
      { source: "/products/wireless-stand-power-bank", destination: "/products/powerbank-outage-wireless-stand", permanent: true },
      { source: "/products/led-triple-port-power-bank", destination: "/products/powerbank-outage-led-3ports", permanent: true },
      { source: "/products/triple-usb-led-power-bank", destination: "/products/powerbank-outage-led-tripleusb", permanent: true },
      { source: "/products/compact-led-power-bank", destination: "/products/powerbank-outage-led-compact", permanent: true },
      { source: "/products/led-power-bank-10000mah", destination: "/products/powerbank-blackout-10000mah-led", permanent: true },
      { source: "/products/led-dual-cell-power-bank-10k", destination: "/products/powerbank-blackout-10000mah-dual", permanent: true },
      { source: "/products/pink-magnetic-power-bank", destination: "/products/powerbank-blackout-magnetic-pink", permanent: true },
      { source: "/products/high-capacity-power-bank-20k", destination: "/products/powerbank-blackout-20000mah", permanent: true },
      { source: "/products/solar-power-bank-20000mah", destination: "/products/solar-powerbank-20000mah-cables", permanent: true },
      { source: "/products/hand-crank-solar-power-bank", destination: "/products/solar-powerbank-handcrank", permanent: true },
      { source: "/products/emergency-solar-radio-crank", destination: "/products/solar-powerbank-emergency-radio", permanent: true },
      { source: "/products/metal-solar-power-bank", destination: "/products/solar-powerbank-metal-outdoor", permanent: true },
      { source: "/products/rugged-solar-power-bank-3usb", destination: "/products/solar-powerbank-rugged-3usb", permanent: true },
      { source: "/products/rugged-solar-power-bank-cables", destination: "/products/solar-powerbank-rugged-cables", permanent: true },
      { source: "/products/magsafe-solar-power-bank-10k", destination: "/products/solar-powerbank-magsafe-10000mah", permanent: true },
      { source: "/products/mini-magsafe-solar-power-bank", destination: "/products/solar-powerbank-magsafe-mini", permanent: true },
      { source: "/products/ultra-slim-solar-power-bank", destination: "/products/solar-powerbank-ultraslim", permanent: true },
      { source: "/products/budget-solar-power-bank-18k", destination: "/products/solar-powerbank-budget-18000mah", permanent: true },
      { source: "/products/solar-power-bank-torch-15k", destination: "/products/solar-powerbank-torch-15000mah", permanent: true },
      { source: "/products/solar-power-bank-20000mah-basic", destination: "/products/solar-powerbank-basic-20000mah", permanent: true },
      { source: "/products/waterproof-solar-power-bank-ip6", destination: "/products/solar-powerbank-waterproof-ip6", permanent: true },
      { source: "/products/waterproof-solar-power-bank-ip55", destination: "/products/solar-powerbank-waterproof-ip55", permanent: true },
      { source: "/products/solar-power-bank-lantern-ip66", destination: "/products/solar-powerbank-lantern-ip66", permanent: true },
      { source: "/products/folding-solar-power-bank", destination: "/products/solar-powerbank-folding", permanent: true },
      { source: "/products/wireless-solar-power-bank", destination: "/products/solar-powerbank-wireless", permanent: true },
      { source: "/products/camping-lantern-power-bank", destination: "/products/solar-powerbank-camping-lantern", permanent: true },
      { source: "/products/solar-lantern-power-bank-3mode", destination: "/products/solar-powerbank-lantern-3mode", permanent: true },
      { source: "/products/solar-speaker-power-bank", destination: "/products/solar-powerbank-bluetooth-speaker", permanent: true },
      { source: "/products/battery-blackout-10kwh-nigeria", destination: "/products/lfp-battery-10kwh", permanent: true },
      { source: "/products/battery-phcn-15kwh-backup", destination: "/products/lfp-battery-15kwh", permanent: true },
      { source: "/products/battery-offgrid-20kwh-solar", destination: "/products/mobile-battery-20kwh", permanent: true },
      { source: "/products/battery-loadshedding-16kwh", destination: "/products/mobile-battery-16kwh", permanent: true },
      { source: "/products/battery-telecom-10kwh-ups", destination: "/products/rack-battery-10kwh", permanent: true },
      { source: "/products/battery-datacenter-15kwh-backup", destination: "/products/rack-battery-15kwh", permanent: true },
      { source: "/products/battery-loadshedding-5kwh-home", destination: "/products/home-battery-5kwh", permanent: true },
      { source: "/products/battery-blackout-10kwh-solar", destination: "/products/solar-battery-10kwh", permanent: true },
      { source: "/products/battery-diesel-replace-16kwh", destination: "/products/solar-battery-16kwh", permanent: true },
      { source: "/products/solar-storage-5kw-blackout", destination: "/products/all-in-one-solar-5kw", permanent: true },
      { source: "/products/battery-replace-leadacid-5kwh", destination: "/products/lifepo4-battery-5kwh", permanent: true },
      { source: "/products/inverter-blackout-6kw-solar", destination: "/products/hybrid-inverter-6kw", permanent: true },
      { source: "/products/inverter-loadshedding-12kw", destination: "/products/hybrid-inverter-12kw", permanent: true },
      { source: "/products/inverter-outdoor-12kw-solar", destination: "/products/solar-inverter-12kw-ip54", permanent: true },
      { source: "/products/inverter-home-6kw-wall", destination: "/products/wall-inverter-6kw", permanent: true },
      { source: "/products/inverter-parallel-6kw-scalable", destination: "/products/parallel-inverter-6kw", permanent: true },
      { source: "/products/inverter-dual-mppt-11kw", destination: "/products/dual-mppt-inverter-11kw", permanent: true },
      { source: "/products/inverter-parallel-11kw-solar", destination: "/products/parallel-inverter-11kw", permanent: true },
      { source: "/products/scooter-nofuel-500w-delivery", destination: "/products/electric-scooter-500w", permanent: true },
      { source: "/products/scooter-nofuel-650w-cargo", destination: "/products/cargo-scooter-650w", permanent: true },
      { source: "/products/ebike-nofuel-350w-folding", destination: "/products/folding-ebike-350w", permanent: true },
      { source: "/products/motorcycle-nopetrol-800w-110km", destination: "/products/electric-motorcycle-800w", permanent: true },
      { source: "/products/motorcycle-nopetrol-800w-cargo", destination: "/products/heavy-motorcycle-800w", permanent: true },
      { source: "/products/ebike-nofuel-350w-fattyre", destination: "/products/fat-tyre-ebike-350w", permanent: true },
      { source: "/products/motorcycle-nofuel-pedal-800w", destination: "/products/pedal-motorcycle-800w", permanent: true },
      { source: "/products/scooter-nofuel-800w-fast", destination: "/products/fast-scooter-800w", permanent: true },
      { source: "/products/scooter-nofuel-800w-200kg", destination: "/products/cargo-scooter-800w", permanent: true },
      { source: "/products/scooter-nofuel-60v-heavy", destination: "/products/heavy-scooter-60v", permanent: true },
      { source: "/products/powerstation-blackout-1kw", destination: "/products/power-station-1kw", permanent: true },
      { source: "/products/solar-generator-loadshedding-1kwh", destination: "/products/solar-generator-1kwh", permanent: true },
      { source: "/products/powerstation-blackout-3kw", destination: "/products/power-station-3kw", permanent: true },
      { source: "/products/powerstation-outage-1kw-portable", destination: "/products/portable-power-station-1kw", permanent: true },
      { source: "/products/powerstation-blackout-1kwh-led", destination: "/products/power-station-led-1kw", permanent: true },
      { source: "/products/powerstation-outage-600w-pocket", destination: "/products/compact-power-station-600w", permanent: true },
      { source: "/products/powerbank-blackout-5000mah-wireless", destination: "/products/wireless-powerbank-5000mah", permanent: true },
      { source: "/products/powerbank-blackout-10000mah-wireless", destination: "/products/wireless-powerbank-10000mah", permanent: true },
      { source: "/products/powerbank-blackout-5000mah-slim", destination: "/products/slim-powerbank-5000mah", permanent: true },
      { source: "/products/powerbank-blackout-5000mah-cables", destination: "/products/powerbank-5000mah-cables", permanent: true },
      { source: "/products/powerbank-loadshedding-10000mah-slim", destination: "/products/slim-powerbank-10000mah", permanent: true },
      { source: "/products/powerbank-loadshedding-10000mah-cables", destination: "/products/powerbank-10000mah-cables", permanent: true },
      { source: "/products/powerbank-loadshedding-5000mah", destination: "/products/powerbank-w152-5000mah", permanent: true },
      { source: "/products/powerbank-outage-5000mah-cables", destination: "/products/powerbank-w152-5000mah-cables", permanent: true },
      { source: "/products/powerbank-outage-10000mah-dualusb", destination: "/products/powerbank-w152-10000mah", permanent: true },
      { source: "/products/powerbank-outage-10000mah-cables", destination: "/products/powerbank-w152-10000mah-cables", permanent: true },
      { source: "/products/powerbank-nepa-5000mah-aluminum", destination: "/products/powerbank-5000mah-aluminum", permanent: true },
      { source: "/products/powerbank-nepa-5000mah-metal", destination: "/products/ultra-slim-powerbank-5000mah", permanent: true },
      { source: "/products/powerbank-nepa-5000mah-display", destination: "/products/powerbank-5000mah-display", permanent: true },
      { source: "/products/powerbank-nepa-10000mah-dualcell", destination: "/products/powerbank-10000mah-aluminum", permanent: true },
      { source: "/products/powerbank-phcn-5000mah-qc", destination: "/products/powerbank-5000mah-qc30", permanent: true },
      { source: "/products/powerbank-phcn-10000mah-digital", destination: "/products/powerbank-10000mah-digital", permanent: true },
      { source: "/products/powerbank-phcn-5000mah-led", destination: "/products/powerbank-5000mah-led", permanent: true },
      { source: "/products/powerbank-phcn-10000mah-led", destination: "/products/powerbank-10000mah-led", permanent: true },
      { source: "/products/powerbank-outage-5000mah-ledslim", destination: "/products/slim-powerbank-5000mah-led", permanent: true },
      { source: "/products/powerbank-outage-10000mah-digital", destination: "/products/powerbank-10000mah-wireless", permanent: true },
      { source: "/products/powerbank-outage-stand-cables", destination: "/products/powerbank-stand-cables", permanent: true },
      
      // Basic Info Pages
      { source: "/about", destination: "/about-us", permanent: true },
      { source: "/contact", destination: "/contact-us", permanent: true },
      { source: "/terms-of-service", destination: "/terms", permanent: true },
      { source: "/shipping", destination: "/terms", permanent: true },
      { source: "/return-policy", destination: "/terms", permanent: true },
      
      // Old Scooter/Bike pages to main products page
      { source: "/category/eScooters-c124119061", destination: "/products", permanent: true },
      { source: "/category/eScooter-parts", destination: "/products", permanent: true },
      { source: "/category/eScooters", destination: "/products", permanent: true },
      { source: "/category/JY-13X-p422276023", destination: "/products", permanent: true },
      { source: "/product/Electric-Bicycle-Barcelona-JY-BCL", destination: "/products", permanent: true },
      { source: "/product/JY-13X", destination: "/products", permanent: true },
      { source: "/product/JY-S358", destination: "/products", permanent: true },
      { source: "/product/JY-R7", destination: "/products", permanent: true },
      { source: "/product/JY-S700", destination: "/products", permanent: true },
      { source: "/product/JY-11X", destination: "/products", permanent: true },
      { source: "/product/JY-R2", destination: "/products", permanent: true },
      { source: "/product/Pure-Solar-Scooter-JY-PS01", destination: "/products", permanent: true },
      { source: "/product/JY-R4", destination: "/products", permanent: true },
      { source: "/product/All-Terrain-Electric-Skate-Board-JY-AT5", destination: "/products", permanent: true },
      { source: "/product/Electric-Harley-Scooter-JY-Q5-with-front-shock-absorber-lamp", destination: "/products", permanent: true },
    ];
  },

  experimental: {
    scrollRestoration: true,
  },
};

export default nextConfig;